### PR TITLE
handleClick checking for e.nativeEvent

### PR DESCRIPTION
**Pull request by jefsnare**
Added a check for e.nativeEvent existence because React.TestUtils.Simulate.Click function breaks on this.

### CODE REVIEW

**Comment by kenwheeler** [comment]
Thanks!

**Comment by jefsnare** [comment]
You're welcome, when is the next release planned?

**Comment by kenwheeler** [comment]
within the week

**Comment by jefsnare** [comment]
@kenwheeler We're several weeks further now..

**Comment by kenwheeler** [comment]
I know I'm the worst. Was traveling for speaking, I'll get this in soon

**Comment by kenwheeler** [comment]
just pushed 1.1.0 @jefsnare

**Comment by jefsnare** [comment]
@kenwheeler Great! Thank you!

**Pull request merged**
