### PR TITLE
add prop for slide index to be shown

### LINKED ISSUE #23: How to set initial slide?
Hello! Thanks for the great React component!

Now, I tried looking on the docs and even on the component itself and it isn't clear to me how to pass the initial slide to the component. This and the 'loop to first/last' is very important for the project I'm currently working on.

_edit:_ Temporarily fixed with this pull request: https://github.com/kenwheeler/nuka-carousel/pull/15

Thanks a lot!

### PR DESCRIPTION
**Pull request by djkirby**
Added a prop ~~`initialSlideIndex`~~ `slideIndex` so you can specify which slide to ~~start with~~ display. For my use case I have some thumbnails and I want the slideshow to start at the thumbnail I click on.

### CODE REVIEW

**Comment by kenwheeler** [comment]
Any interest in amending this PR to just be slideIndex, and if supplied, have the slide managed externally? you can listen in componentWillReceiveProps and change the slide in there.

**Comment by djkirby** [comment]
Sure thing, I wasn't sure which way to go with it but I'm cool with that.

**Comment by djkirby** [comment]
Only thing w/ controlling the slide from the outside is you can't use the built in prev/next buttons :disappointed:

**Comment by kenwheeler** [comment]
yes you can. manage the current slide using state. if new props come in that are different from the last props, setState on current slide. make them mutually overrideable

**Comment by djkirby** [comment]
I didn't realize there was a `afterSlide` method I can hook into to update the state on the outside when it changes internally.

**Comment by djkirby** [comment]
Updated @kenwheeler. Example use here:

```jsx
'use strict';

import Carousel from '../src/carousel';
import React from 'react';
import ReactDom from 'react-dom';

window.React = React;

const App = React.createClass({
  mixins: [Carousel.ControllerMixin],
  getInitialState() { return { slideIndex: 0 }; },
  render() {
    return (
      <div style={{width: '50%', margin: 'auto'}}>
        <Carousel
          ref="carousel"
          data={this.setCarouselData.bind(this, 'carousel')}
          slideIndex={this.state.slideIndex}
          afterSlide={newSlideIndex => this.setState({ slideIndex: newSlideIndex })}>
          <img src="http://placehold.it/1000x400&text=slide1"/>
          <img src="http://placehold.it/1000x400&text=slide2"/>
          <img src="http://placehold.it/1000x400&text=slide3"/>
          <img src="http://placehold.it/1000x400&text=slide4"/>
          <img src="http://placehold.it/1000x400&text=slide5"/>
          <img src="http://placehold.it/1000x400&text=slide6"/>
        </Carousel>
        <button onClick={() => this.setState({ slideIndex: 0 })}>1</button>
        <button onClick={() => this.setState({ slideIndex: 1 })}>2</button>
        <button onClick={() => this.setState({ slideIndex: 2 })}>3</button>
        <button onClick={() => this.setState({ slideIndex: 3 })}>4</button>
        <button onClick={() => this.setState({ slideIndex: 4 })}>5</button>
        <button onClick={() => this.setState({ slideIndex: 5 })}>6</button>
      </div>
    )
  }
});

const content = document.getElementById('content');

ReactDom.render(<App/>, content)
```

**Comment by kenwheeler** [comment]
Can you rebase this? Sorry.

**Comment by djkirby** [comment]
np, rebased

**Comment by kenwheeler** [comment]
Thanks so much!

**Comment by agroves333** [comment]
Previously to adding the slideIndex property, I was just calling goToSlide(n) on the ref of the carousel and keeping track of the slide index in a parent state. This worked well, but when updating the carousel to the new version that has this slideIndex prop, there aren't any slide animations. It just immediately changes the slide. Any thoughts?

**Pull request merged**
